using OneClickEcho.Domain.CampaignLeadAggregate.Repositories;

namespace OneClickEcho.Application.Campaign.Queries.CountCampaignLeadsByStatus;

public record CountCampaignLeadsByStatusResponse(CountCampaignLeadsByStatusDto CountCampaignLeadsByStatusDto);