@host = https://localhost:5100

### Get Token
POST {{host}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
username = stefan.petrovic@blackbird.rs &
password = Testing123! &
scope = offline_access

> {%
    client.global.set("AccessToken", response.body.access_token);
    client.global.set("RefreshToken", response.body.refresh_token);
%}

### Create User
POST {{host}}/api/User
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "companyId": "b565ce71-a92f-4313-921c-11ee1e513a97",
  "role": 2,
  "email": "stefan.petrovic2@blackbird.rs"
}

### Force Reset Password
POST {{host}}/api/User/ForcePasswordUpdate
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "UserId": "4296760c-f55a-4335-afd7-99c5bf5ae18c",
  "NewPassword": "Testing123."
}

### Get Token with new password
POST {{host}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
username = stefan.petrovic1@blackbird.rs &
password = Testing123! &
scope = offline_access

> {%
    client.global.set("AccessToken", response.body.access_token);
    client.global.set("RefreshToken", response.body.refresh_token);
%}


### Reset Password
POST {{host}}/api/User/PasswordUpdate
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "UserId": "4296760c-f55a-4335-afd7-99c5bf5ae18c",
  "Password": "Testing123.",
  "NewPassword": "Testing123!"
}

### Get Token with new password
POST {{host}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
username = stefan.petrovic1@blackbird.rs &
password = Testing123! &
scope = offline_access

> {%
    client.global.set("AccessToken", response.body.access_token);
    client.global.set("RefreshToken", response.body.refresh_token);
%}
